databases:
  - name: bookstore_db
    databaseName: bookstore_db
    user: bookstore_user
    plan: free

services:
  - type: web
    name: bookstore
    env: python
    plan: free
    buildCommand: |
      pip install poetry
      poetry install --no-interaction --no-ansi
      poetry run python manage.py migrate
      poetry run python manage.py collectstatic --noinput
    startCommand: poetry run gunicorn bookstore.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bookstore_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DJANGO_ALLOWED_HOSTS
        value: bookstore.onrender.com
      - key: PYTHON_VERSION
        value: 3.12.7