# Generated by Django 5.2.1 on 2025-05-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["id"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"]},
        ),
    ]
