name: Python Pull Request Workflow
on: [push]
jobs:
  qa:
    name: Quality check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry and dependencies
        run: |
          pip install -U pip
          pip install poetry
          poetry install
        env:
          POETRY_VIRTUALENVS_CREATE: false
      - name: Test
        run: |
          poetry run python manage.py test
      - name: Wemake Python Styleguide
        uses: wemake-services/wemake-python-styleguide@latest
        with:
          reporter: 'github-pr-review'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}